### ISSUE TITLE
KeyError: 'seg2d'

### ISSUE THREAD

**Issue by Ivan-VV** [thusiyuan/cooperative_scene_parsing#18]
Thanks for your great work!
I get the error when I run the sunrgbd/sunrgbd_process.py in step 4 of Data.
`Traceback (most recent call last):
  File "preprocess/sunrgbd/sunrgbd_process.py", line 666, in <module>
    main()
  File "preprocess/sunrgbd/sunrgbd_process.py", line 660, in main
    prepare_data(False, shift=False)
  File "preprocess/sunrgbd/sunrgbd_process.py", line 75, in prepare_data
    sequence = readsunrgbdframe(image_id=i+1)
  File "/home/data4t/wyf/cooperative_scene_parsing/preprocess/sunrgbd/sunrgbd_parser.py", line 136, in readsunrgbdframe
    data_frame = SUNRGBDData(img_info['K'], img_info['R_ex'], img_info['R_tilt'], img_info['bdb2d'], img_info['bdb3d'], img_info['gt3dcorner'], img_info['imgdepth'], img_info['imgrgb'], img_info['seg2d'], img_info['sequence_name'], image_id, scene_category)
KeyError: 'seg2d'`

Then I print the _keys_ of _img_info_ and get the result as follows.
`['R_ex', 'seg2d_path', 'sensor', 'sequence_name', 'imgrgb_path', 'gt3dcorner', 'R_tilt', 'bdb2d', 'bdb3d', 'K', 'imgdepth_path']
`
It seems that the dict object _img_info_ doesn't have a key called "_seg2d_". But I have completed the previous three steps according to the instruction
Could you please tell me what I should do to solve this problem? Thank you very much!

**Comment by lx6527562** [comment]
Hello, I have the same problem, how can I solve it?
