### ISSUE TITLE
FileNotFoundError: 'metadata/sunrgbd/size_avg_category.pickle'

### ISSUE THREAD

**Issue by mitraavi** [thusiyuan/cooperative_scene_parsing#9]
While exploring this project i just could not find following error:

    FileNotFoundError: [Errno 2] No such file or directory: 'metadata/sunrgbd/size_avg_category.pickle' 

Full Traceback message is given below:
----------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 53, in <module>
    bins_tensor = to_dict_tensor(dataset_config.bins(), if_cuda=opt.cuda)
  File "cooperative_scene_parsing-master/config.py", line 74, in bins
    avg_size = pickle.load(open(template_path, 'r'))
FileNotFoundError: [Errno 2] No such file or directory: 'metadata/sunrgbd/size_avg_category.pickle'
------------------------------------------------------------
Any help to solve above issues is highly appreciated.
Thank You

**Comment by majiayao-roborock** [comment]
i have the same problem,do you fix it?@mitraavi

**Comment by Harvey-Mei** [comment]
same problem :(

**Comment by Harvey-Mei** [comment]
> same problem :(

oh, i see, this file in the compressed files sunrgbd_preprocess.zip
